### ISSUE TITLE
Error removing constraints

### ISSUE THREAD

**Issue by sfleuren** [coin-or/python-mip#1]
Been using this package with pleasure.

However, I may have detected an error. When removing a constraint I got the following error:

File "/usr/local/lib/python3.7/site-packages/mip/cbc.py", line 767, in remove_constrs
    cbclib.Cbc_deleteRows(self._model, idx)
TypeError: 'void(*)(void *, int, int *)' expects 3 arguments, got 2

If the interface from the link below is used, then indeed three arguments are expected:
https://www.coin-or.org/Doxygen/CoinAll/_cbc___c___interface_8h.html#a769db426ae492baea43be8c2d459924

I suspect the same holds for removing a variable.

**Comment by tuliotoffolo** [comment]
Dear,

Thank you very much for your message.
We will address this error immediately and push an update by tomorrow.

Best regards,
Túlio

Em 25 de mai de 2019 18:03 -0300, sfleuren <notifications@github.com>, escreveu:

**Comment by h-g-s** [comment]
Hi @sfleuren , just release 1.1.2, it seems to be working now, could you please check ?

**Comment by sfleuren** [comment]
It does seem to work now!

**Comment by h-g-s** [comment]
good ! could you please close the issue ?
