### ISSUE TITLE
Reintroduction of in-place-operators for LinExpr

### ISSUE THREAD

**Issue by sebheger** [coin-or/python-mip#108]
With release 1.9.0 (in comparison to 1.8.2) the in-place-operators of LinExpr have been set to "Deprecated". I would suggest to reintroduce it again. We have introduced CBC to our company optimization platform (besides a commercial optimizer) a few weeks ago and would be glad if interfaces keep as stable as possible. I am wondering why this nice and convenient feature (which APIs of commercial solvers also provide) has been removed within the changes for #100.

**Comment by jurasofish** [comment]
To answer your question directly, in-place mutation was removed to allow performance improvements when multiplying by 1 or 0 in #98.

In a more general sense, I think two things this library could do to really strongly improve quality and consistency are:
- use feature branches, as @tommyod really pushed for in #41.
- properly use semantic versioning.

Semantic versioning would have at least mitigated this issue as it would have pushed the version to 2.x.x (as I said https://github.com/coin-or/python-mip/issues/98#issuecomment-627655070). I think users (such as you @sebheger) are assuming that this library follows semantic versioning. That's a reasonable assumption - I'd make the same - but it's not the case.

I really like this library, which is why I'm helping out a little with development, but the development process is very cavalier. I think it's really important to get this sort of stuff nailed down considering the growing public use of this library (which isn't surprising, it's a great library).

**Comment by sebheger** [comment]
In general, I totally agree with what @jurasofish said. Additionally, I would suggest to not deliver "dirty versions" of CBC within the release. You could incrementally deliver a new, official version with a minor update (1.9.x) corresponding to the right semantic versioning.

In this case, regarding the deprecated function, I would suggest adding the functionality back. Based on a first look into 3772f068d76638622b30972b14cbc10dfb5e102d there will be no need to remove it. As I noticed from the discussion in #98, the in-place operation is slow. But in my option, this is no cause to remove it ;-)

**Comment by tommyod** [comment]
> I think it's really important to get this sort of stuff nailed down considering the growing public use of this library (which isn't surprising, it's a great library).

Agreed. Also, I think many talented developers that might be interested in contributing simply move on when they see that the development process does not follow standard practice. This creates a negative feedback loop.

**Comment by tuliotoffolo** [comment]
Hello @sebheger and @jurasofish,
I was away and did not follow #98 and #100 at all. I only interfered in the very end when I noticed that numpy was added as a dependency (although we don't need to do so currently).

After your message I read all code changes. I should tell you that I myself use in-place very often... Anyway, @jurasofish is right: we must and **will** improve the development process. 

Concerning in-place operators: I agree that they represent a very useful functionality and should be added back.

**Comment by h-g-s** [comment]
Hello everyone,

Well, If in-place operators are really useful for building models (personally I don't use them)   then there should exist some examples and tests using them.

With enough tests we can keep a rapid release cycles without the risk of breaking important things.

**Comment by jurasofish** [comment]
> Hello everyone,
> 
> Well, If in-place operators are really useful for building models (personally I don't use them) then there should exist some examples and tests using them.
> 
> With enough tests we can keep a rapid release cycles without the risk of breaking important things.

Agreed, features should have tests

**Comment by tuliotoffolo** [comment]
Yes, definitely! I will add some models implemented using this feature.
Em 26 de mai de 2020 19:55 -0300, Michael Jurasovic <notifications@github.com>, escreveu:

**Comment by sebheger** [comment]
@h-g-s As requested I have found an example where somebody uses in-place operators to build an expression. Honestly, there is also an add function available to extend the LinExpr with the content of another expr.  But here a combination of in-place and sum-iteration is used, for me it is clear and readable. So I see no urgent need to refactor this piece of code ...

```python
demand_expr = LinExpr()
demand_expr += supply_demand_data.loc[group, 'Demand_{}'.format(time)]
demand_expr += sum(demand_shift_plus[(group, time)])
demand_expr -= sum(demand_shift_minus[(group, time)])
```

**Comment by tuliotoffolo** [comment]
Excellent! I agree that it is readable as it is.

Em ter., 30 de jun. de 2020 às 09:41, Sebastian Heger <
notifications@github.com> escreveu:

**Comment by tuliotoffolo** [comment]
Dear all,
After some productive discussions with Haroldo, we would like to debate this subject again and close this issue.

I am in favor of reintroducing the in-place operations for LinExpr, but would like to hear arguments from those who are against the reintroduction. I do believe we are losing too much for a rather limited gain (improvements when multiplying by 1 or 0).
