### ISSUE TITLE
Solver hangs - No solution found this major pass 

### ISSUE THREAD

**Issue by masoudML** [coin-or/python-mip#120]
Hi,

I have been working on an MILP and I have been getting "No solution found with major pass" and  " Cbc0038I Before mini branch and bound, 2 integers at bound fixed and 22 continuous" (see below). The problem is the solver hangs and doesn't continue beyond this point. In some of the problematic runs (not all), when we increase the opt_tol to 1e-5 or 1e-4 it solves and finds the solution in the major pass. I am wondering if you can point out the possibilities for this so we can better find a solution to this problem. PS: we tried both mip==1.9.1 and 1.9.2. 

Thanks! 

Coin3007W ### CoinLpIO::checkRowNames(): non distinct or missing row names or objective function name.
Now using default row names.
Starting solution of the Linear programming relaxation problem using Dual Simplex

Coin0506I Presolve 65 (-50) rows, 68 (-23) columns and 164 (-85) elements
Clp0014I Perturbing problem by 0.001% of 0.21756412 - largest nonzero change 0.0007721478 ( 49.251696%) - largest zero change 0.00076793457
Clp0006I 0  Obj 2.2586235 Primal inf 697.79762 (16) Dual inf 0.36188959 (5)
Clp0000I Optimal - objective value -0.25526765
Coin0511I After Postsolve, objective -0.25526765, infeasibilities - dual 0 (0), primal 0 (0)
Clp0032I Optimal objective -0.2552676458 - 22 iterations time 0.002, Presolve 0.00

Starting MIP optimization
maxSavedSolutions was changed from 0 to 10
Continuous objective value is -0.255268 - 0.00 seconds
Cgl0002I 3 variables fixed
Cgl0003I 0 fixed, 0 tightened bounds, 7 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 1 strengthened rows, 0 substitutions
Cgl0004I processed model has 38 rows, 50 columns (9 integer (9 of which binary)) and 115 elements
Coin3009W Conflict graph built in 0.000 seconds, density: 0.337%
Cgl0015I Clique Strengthening extended 0 cliques, 0 were dominated
Cbc0038I Initial state - 4 integers unsatisfied sum - 0.951873
Cbc0038I Pass   1: suminf.    0.00000 (0) obj. 0.064487 iterations 12
Cbc0038I Solution found of 0.064487
Cbc0038I Relaxing continuous gives 0.0644732
Cbc0038I Before mini branch and bound, 5 integers at bound fixed and 22 continuous
Cbc0038I Full problem 38 rows 50 columns, reduced to 11 rows 13 columns
Cbc0038I Mini branch and bound improved solution from 0.0644732 to -0.0974106 (0.01 seconds)
Cbc0038I Round again with cutoff of -0.109617
Cbc0038I Pass   2: suminf.    0.51000 (3) obj. -0.109617 iterations 10
Cbc0038I Pass   3: suminf.    0.22318 (3) obj. -0.109617 iterations 11
Cbc0038I Pass   4: suminf.    0.06378 (2) obj. -0.109617 iterations 17
Cbc0038I Pass   5: suminf.    0.13146 (2) obj. -0.109617 iterations 7
Cbc0038I Pass   6: suminf.    0.13146 (2) obj. -0.109617 iterations 0
Cbc0038I Pass   7: suminf.    0.13146 (2) obj. -0.109617 iterations 0
Cbc0038I Pass   8: suminf.    0.89172 (4) obj. -0.109617 iterations 4
Cbc0038I Pass   9: suminf.    0.51159 (3) obj. -0.109617 iterations 1
Cbc0038I Pass  10: suminf.    0.51159 (3) obj. -0.109617 iterations 1
Cbc0038I Pass  11: suminf.    0.51159 (3) obj. -0.109617 iterations 1
Cbc0038I Pass  12: suminf.    0.06378 (2) obj. -0.109617 iterations 7
Cbc0038I Pass  13: suminf.    0.06378 (2) obj. -0.109617 iterations 0
Cbc0038I Pass  14: suminf.    0.06378 (2) obj. -0.109617 iterations 0
Cbc0038I Pass  15: suminf.    0.10998 (2) obj. -0.109617 iterations 7
Cbc0038I Pass  16: suminf.    0.22318 (3) obj. -0.109617 iterations 10
Cbc0038I Pass  17: suminf.    0.31479 (4) obj. -0.109617 iterations 1
Cbc0038I Pass  18: suminf.    0.31479 (4) obj. -0.109617 iterations 0
Cbc0038I Pass  19: suminf.    0.69492 (5) obj. -0.109617 iterations 3
Cbc0038I Pass  20: suminf.    0.06378 (2) obj. -0.109617 iterations 15
Cbc0038I Pass  21: suminf.    0.13146 (2) obj. -0.109617 iterations 7
Cbc0038I Pass  22: suminf.    0.13146 (2) obj. -0.109617 iterations 0
Cbc0038I Pass  23: suminf.    0.51159 (3) obj. -0.109617 iterations 2
Cbc0038I Pass  24: suminf.    0.51159 (3) obj. -0.109617 iterations 0
Cbc0038I Pass  25: suminf.    0.51159 (3) obj. -0.109617 iterations 2
Cbc0038I Pass  26: suminf.    0.06378 (2) obj. -0.109617 iterations 7
Cbc0038I Pass  27: suminf.    0.13146 (2) obj. -0.109617 iterations 8
Cbc0038I Pass  28: suminf.    0.13146 (2) obj. -0.109617 iterations 0
Cbc0038I Pass  29: suminf.    0.13146 (2) obj. -0.109617 iterations 0
Cbc0038I Pass  30: suminf.    0.13146 (2) obj. -0.109617 iterations 0
Cbc0038I Pass  31: suminf.    0.13146 (2) obj. -0.109617 iterations 0
Cbc0038I No solution found this major pass
Cbc0038I Before mini branch and bound, 2 integers at bound fixed and 22 continuous

**Comment by h-g-s** [comment]
We can only debug if you provide us the data/code.

**Comment by sebheger** [comment]
I will close this issue, as no data/code was provided for nearly 2 years.
