### ISSUE TITLE
`model.write` output invalid lp file

### ISSUE THREAD

**Issue by vang1ong7ang** [coin-or/python-mip#130]
**Describe the bug**

if you call something like `model.add_constr(linexpr >= 0)`, **actually the `linexpr` is a constant `LinExpr` with value `0`**, and then call `model.write(lpfile)`, you will see a line `constr(0):  >= -0` in the lp file, which makes the lp file invalid.

**To Reproduce**
Steps to reproduce the behavior **please include attached any files needed to reproduce the error**. We can only help you if we can reproduce the error ourselves and debug.

```
from mip import Model

m = Model()
x = m.add_var()

# sometimes y is indeed a constant LinExpr 0
# for example
# y = x - x
# y = xsum([])
# ...

y = x - x
m.add_constr(y >= 0)
m.objective = x
m.write('out.lp')
```

```
\Problem name: 

Minimize
OBJROW: var(0)
Subject To
constr(0):  >= -0
Bounds
End
```

**Expected behavior**

**Desktop (please complete the following information):**
 - Operating System, version:
 - Python version:
 - Python-MIP version (we recommend you to test with the latest version):  

**Additional context**

**Comment by tuliotoffolo** [comment]
I talked with @h-g-s about this. We both agree that we shouldn't allow creating constraints with empty linear expressions. Therefore, the code below should throw an `InvalidLinExpr` exception.  Something like "*An empty linear expression cannot be used as a constraint*".

```
y = x - x
m.add_constr(y >= 0)
```

I will update the code to raise the exception in such cases.

**Comment by tuliotoffolo** [comment]
Some people may be currently using empty linear expressions to create constraints in their models... As to avoid problems, I will leave this issue open for the moment. Concerning the LP file, I should mention that it is generated by the solver itself.

**Comment by vang1ong7ang** [comment]
> I talked with @h-g-s about this. We both agree that we shouldn't allow creating constraints with empty linear expressions. Therefore, the code below should throw an `InvalidLinExpr` exception. Something like "_An empty linear expression cannot be used as a constraint_".
> 
> ```
> y = x - x
> m.add_constr(y >= 0)
> ```
> 
> I will update the code to raise the exception in such cases.

But actually, people may not intentionally create empty linear expressions. Someone may use `xsum` or some other operations and accidentally an empty linear expression is created.

For example, if I launch a service to calculate the maximum `x` with the following constraints where `a`, `b`, `c`, `d` are rational numbers provided from user input.

```python
def cal(a, b, c, d):
    s = m.add_var()
    t = m.add_var()
    x = a * s + b * t
    y = c * s + d * t
    m.add_constr(x + y >=0)
```

As a service, I never know what is the exact user input. Users may provide `a = 1; b =1; c = 1; d = 1;` or `a = 1; b =1; c = -1; d = 1;`.
