### ISSUE TITLE
Support Gurobi Cloud

### ISSUE THREAD

**Issue by rschwarz** [coin-or/python-mip#141]
Currently, `python-mip` can be used to solve problems with Gurobi on the local machine.
A recent [mailing-list question](https://groups.google.com/forum/#!topic/python-mip/xkrhxqnHW9M) asked about corresponding support for Gurobi Cloud.

It's true that this still requires a local Gurobi installation and that a different call must be made to create a Gurobi environment.
Namely, in place of [GRBloadenv](https://github.com/coin-or/python-mip/blob/master/mip/gurobi.py#L356), the related [GRBc_loadcloudenv](https://www.gurobi.com/documentation/9.0/refman/c_loadcloudenv.html) should be called, passing the license details as strings.

It might make sense to create a specific constructor for this, or else add a separate `SolverGurobiCloud` class for that purpose.
I'd like to work on a PR for this feature, but I don't currently have a (cloud) license for testing.

**Comment by h-g-s** [comment]
Hi @rschwarz ,  this would be nice indeed ! Does gurobi has some temporary cloud license where you could test it ?

**Comment by rschwarz** [comment]
I don't think so, at least not in an automated way (the trial process requires manual confirmation). But I will reconsider this issue whenever I have access to a commercial Gurobi license in the future.

**Comment by PMLP-novo** [comment]
I think Gurobi should be interested in providing you that access. It could give my project the option to use Gurobi. Anybody knows somebody that could provide the access? @mattmilten

**Comment by mattmilten** [comment]
A simpler way is to specify the cloud via the license file. This should work without changing the code - you just use a cloud license as your default license file and the environment should start as a cloud environment.

**Comment by rschwarz** [comment]
This can be closed as the feature is already available after all.
