### ISSUE TITLE
CBC solver getting stuck

### ISSUE THREAD

**Issue by jerak** [coin-or/python-mip#145]
Hi all,

I'm currently experiencing some issues when using the CBC solver from Python-MIP (version 1.10.0, but also tried other versions). When switching on the logging, the latest logging I receive is:
```
Starting MIP optimization
Cgl0003I 0 fixed, 0 tightened bounds, 90 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 29 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 7 strengthened rows, 0 substitutions
Cgl0004I processed model has 239 rows, 293 columns (249 integer (181 of which binary)) and 1272 elements
Coin3009W Conflict graph built in 0.000 seconds, density: 0.240%
Cgl0015I Clique Strengthening extended 0 cliques, 0 were dominated
Cbc0038I Initial state - 68 integers unsatisfied sum - 27.9242
Cbc0038I Pass   1: suminf.    0.54000 (3) obj. 1.1061e+06 iterations 130
Cbc0038I Pass   2: suminf.    0.04000 (2) obj. 1.10615e+06 iterations 4
Cbc0038I Pass   3: suminf.    0.04000 (2) obj. 1.10615e+06 iterations 3
Cbc0038I Solution found of 1.10615e+06
Cbc0038I Relaxing continuous gives 1.10615e+06
Cbc0038I Cleaned solution of 1.10615e+06
Cbc0038I Before mini branch and bound, 136 integers at bound fixed and 79 continuous
Cbc0038I Full problem 239 rows 293 columns, reduced to 144 rows 57 columns
```

After that, no new logging appears, even though the maximum runtime should be limited to 10 seconds. Increasing this didn't help. I've attached the lp formulation of the problem, but directly running that results in the problem being solved, which makes it hard to debug. For your understanding, I'm solving multiple MIP's sequentially, which normally works, but some iterations are getting stuck. 

I'm running this via a docker container.

[lp_formulation.txt](https://github.com/coin-or/python-mip/files/5309955/lp_formulation.txt)

Please let me know if additional information is required.

Thank you in advance,

Jeroen

**Comment by sebheger** [comment]
Works fine with latest release 1.14.0.
