### ISSUE TITLE
Observed Segfault with model that is "large" in the case of CBC

### ISSUE THREAD

**Issue by sebheger** [coin-or/python-mip#157]
**Describe the bug**
Signal SIGSEV. See the log for details. [failed_log.txt](https://github.com/coin-or/python-mip/files/5493403/failed_log.txt)

**To Reproduce**
Used provided .lp-file [segfault_mip.lp.zip](https://github.com/coin-or/python-mip/files/5493407/segfault_mip.lp.zip).

**Expected behavior**
CBC part should not run into SIGSEV.

**Desktop (please complete the following information):**
 - Operating System, version: OSX 10.15.7
 - Python version: 3.7.4
 - Python-MIP version (we recommend you to test with the latest version):  12.0

**Additional context**
Seems to be similar or even identical to #139

**Comment by h-g-s** [comment]
HI @sebheger ,  I'm able to reproduce it in a MacOS. I recently added some code to CBC to print the stack trace on a failure.  I can see the method that failed,  but not the exact line :/   I'll try to investigate more.

**Comment by h-g-s** [comment]
ERROR while running Cbc. Signal SIGSEGV caught. Getting stack trace.
0   cbc-c-darwin-x86-64.dylib           0x0000000114fe9727 _Z15CbcCrashHandleri + 327
1   libsystem_platform.dylib            0x00007fff70c215fd _sigtramp + 29
2   ???                                 0x0000000000000000 0x0 + 0
3   cbc-c-darwin-x86-64.dylib           0x0000000115074e7e _ZN8CbcModel15setBestSolutionEPKdidb + 1662
4   cbc-c-darwin-x86-64.dylib           0x0000000114fccb8f _Z8CbcMain1iPPKcR8CbcModelPFiPS2_iER19CbcSolverUsefulData + 106015
5   cbc-c-darwin-x86-64.dylib           0x0000000114f30215 Cbc_solve + 4805
6   libffi.dylib                        0x00007fff6e7ca905 ffi_call_unix64 + 85
7   ???                                 0x0000000114f02038 0x0 + 4646248504




ERROR while running Cbc. Signal SIGABRT caught. Getting stack trace.
0   cbc-c-darwin-x86-64.dylib           0x0000000114fe9727 _Z15CbcCrashHandleri + 327
1   libsystem_platform.dylib            0x00007fff70c215fd _sigtramp + 29
2   ???                                 0x315245695f325350 0x0 + 3553979374819758928
3   libsystem_c.dylib                   0x00007fff70af7808 abort + 120
4   cbc-c-darwin-x86-64.dylib           0x000000011546db10 _ZNSt3__16vectorINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEENS4_IS6_EEEC2ERKS8_.cold.1 + 0
5   cbc-c-darwin-x86-64.dylib           0x0000000114fe97cf _Z15CbcCrashHandleri + 495
6   libsystem_platform.dylib            0x00007fff70c215fd _sigtramp + 29
7   ???                                 0x0000000000000000 0x0 + 0
8   cbc-c-darwin-x86-64.dylib           0x0000000115074e7e _ZN8CbcModel15setBestSolutionEPKdidb + 1662
9   cbc-c-darwin-x86-64.dylib           0x0000000114fccb8f _Z8CbcMain1iPPKcR8CbcModelPFiPS2_iER19CbcSolverUsefulData + 106015
10  cbc-c-darwin-x86-64.dylib           0x0000000114f30215 Cbc_solve + 4805
11  libffi.dylib                        0x00007fff6e7ca905 ffi_call_unix64 + 85
12  ???                                 0x0000000114f02038 0x0 + 4646248504

**Comment by h-g-s** [comment]
should be fixed in master, I'll run some additional tests and release a new version

**Comment by h-g-s** [comment]
Should be fixed in 1.13, I'll close for now, please test.

**Comment by sebheger** [comment]
Tested successfully
