### ISSUE TITLE
Does Continuous variable default to be > 0?

### ISSUE THREAD

**Issue by zuzhaoye** [coin-or/python-mip#159]
**Describe the bug**
Does Continuous variable default to be > 0?

**To Reproduce**
```
from mip import *

m = Model(sense=MINIMIZE, solver_name=CBC) # use GRB for Gurobi
n = 5
x = [m.add_var(var_type=CONTINUOUS) for i in range(n)]

for i in range(n):
    m += x[i] <= -1
    m += x[i] >= -2
    
m.objective = xsum(x[i] for i in range(n))
    
m.max_gap = 0.05
status = m.optimize(max_seconds=300)

print(status)
print(m.objective_value)
```

**Expected behavior**
Expect:
```
OptimizationStatus.OPTIMAL
-10
```
But get:
```
OptimizationStatus.INFEASIBLE
None
```
**Desktop (please complete the following information):**
 - Operating System, version: Win 10, 64bit
 - Python version: 3.7
 - Python-MIP version (we recommend you to test with the latest version):  1.12.0

**Additional context**

If I add a lower bound in definition, then everything works.

```
M = 1e5 # any large number
x = [m.add_var(var_type=CONTINUOUS, lb = -M) for i in range(n)]
```

**Comment by jurasofish** [comment]
> Does Continuous variable default to be > 0?

yea, https://docs.python-mip.com/en/latest/classes.html#mip.Model.add_var

**Comment by zuzhaoye** [comment]
> 
> 
> > Does Continuous variable default to be > 0?
> 
> yea, https://docs.python-mip.com/en/latest/classes.html#mip.Model.add_var

Oh, I see. You default lb to be 0. No more question, appreciate it.
