### ISSUE TITLE
Optimization time: can multiprocessing be used

### ISSUE THREAD

**Issue by adamdharris** [coin-or/python-mip#16]
I have a model with ~300,000 rows x 40,000 columns.  Is it possible to use multiprocessing similar to speed up the optimization?

**Comment by sebheger** [comment]
Both CBC and Gurobi can use multiple threads for solving the problem. I guess you can also build your own python multi-threaded application to build the model.

By the way, I will close the issue. @adamdharris If there are any questions open, please reopen this issue.
