### ISSUE TITLE
Get slack from constraint after optimization

### ISSUE THREAD

**Issue by ahowe42** [coin-or/python-mip#20]
I'm playing around with the simple binary knapsack demo, and want to compute the total knapsack weight (and slack) at the end of optimization. It seems this should be available, as the `constr` object has a `slack` attribute. However, when I execute `m.constrs[0].slack` (`m` is my model object), I get this:
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-27-729f9da1c948> in <module>
----> 1 m.constrs[0].slack

d:\Continuum\anaconda3\lib\site-packages\mip\model.py in slack(self)
     85         """
     86 
---> 87         return self.__model.solver.constr_get_slack(self)
     88 
     89     @property

d:\Continuum\anaconda3\lib\site-packages\mip\cbc.py in constr_get_slack(self, constr)
    991         rhs = float(cbclib.Cbc_getRowRHS(self._model, constr.idx))
    992         activity = float(pac[constr.idx])
--> 993         if constr.sense == "<":
    994             return rhs - activity
    995         elif constr.sense == ">":

AttributeError: 'Constr' object has no attribute 'sense'`

The error is confirmed, as I get `AttributeError: 'Constr' object has no attribute 'sense'` if I execute `m.constrs[0].sense`. This seems odd, as the documentation states that a `constr` is a `linexpr` object with the `sense` attribute, as opposed to an objective: "Note that the only difference of adding a constraint is the lack of a sense and a rhs.". 

What am I missing?

**Comment by h-g-s** [comment]
Hello, just fixed in 1.5.2, could you test ?

**Comment by ahowe42** [comment]
Looks good. Executing `m.constrs[0].slack` now returns the slack on that constraint as expected. Thanks!
