### ISSUE TITLE
Can't read a .lp.gz formatted file

### ISSUE THREAD

**Issue by mkurtzsd** [coin-or/python-mip#204]
**Describe the bug**
The library currently can open and read an MPS file that is compressed as a .gz file (.mps.gz extension). The library throws an error is attempting to pass in a LP file that is compressed as a .gz file (.lp.gz extension). However, by modifying the `model_ext` variable to be: `model_ext = [".lp", ".mps", ".mps.gz", ".lp.gz"]` in the model.py file's `read(self: "Model", path: str):` method, the library will read and properly parse the file.

**To Reproduce**
Submit a model stored in a .lp.gz to the read method. Library will throw an exception stating that "Use .lp, .mps, .sol or .mst as file extension to indicate the file format."

**Expected behavior**
It would be very helpful to be able to submit a gzipped LP file without receiving the exception.

**Desktop (please complete the following information):**
 - Operating System, version: Linux CentOS 7
 - Python version: Python 3.7.9
 - Python-MIP version (we recommend you to test with the latest version):  1.13.0

**Additional context**
Nothing else to add.

**Comment by tuliotoffolo** [comment]
Thanks for pointing this out, @mkurtzsd. We've updated the code following your suggestion.
