### ISSUE TITLE
Upper bound argument does not seem to have any effect on the assignment of binary variables

### ISSUE THREAD

**Issue by kaibir** [coin-or/python-mip#205]
**Describe the bug**

If adding an upper bound via 'ub=' argument to binary variable it has no effect.

**To Reproduce**

To reproduce use this very simple model:

```python
my_model = mip.Model(name="my model", sense="MAX", solver_name="CBC")
var = my_model.add_var(name="ZeroVar", var_type=mip.BINARY, obj=1, ub=0.0)
my_model.optimize()
```
The objective value is 1.0 and also ZeroVar is 1.0

**Expected behavior**
I would have expected that ZeroVar is 0.0 and also the objective value is.

If I add the additional constraint (which is in my eyes exactly what the ub should do)
`my_model.add_constr(var <= 0)`

I get the expected result.

I know it may not make much sense to add an upper limit of 0 to a binary variable, but ignoring the upper limit for binary variables is not right in my eyes either.

**Desktop (please complete the following information):**
 - Operating System, version: MacOS BigSur 11.2.3
 - Python version: 3.9.0
 - Python-MIP version: 1.13.0  

**Additional context**

**Comment by tuliotoffolo** [comment]
Thanks, @kaibir.
Indeed, the code was forcing lb=0 and ub=1 for all binary variables:

```python
if var_type == mip.BINARY:
    lb = 0.0
    ub = 1.0
```

Now `ub` is set to 1.0 only when the default value `mip.INF` is passed.

**Comment by christian2022** [comment]
What about lb=1?

**Comment by tuliotoffolo** [comment]
The default is lb=0, but the user may now set lb=1. Here's the code that replaces the previous one:

```python
if var_type == mip.BINARY:
    if ub == mip.INF:
        ub = 1.0
    if not (0.0 <= lb <= 1.0 and 0.0 <= ub <= 1.0):
        raise ValueError("Invalid bounds for a binary variable")
```
