### ISSUE TITLE
m.optimize() returns OPTIMAL, but the found minimum is wrong.

### ISSUE THREAD

**Issue by tooflesswulf** [coin-or/python-mip#210]
**Describe the bug**
Calling `m.optimize()` returns `OptimizationStatus.OPTIMAL`, but the solution is not optimal.

**To Reproduce**
I have a MIP problem defined here:
[problem.py.zip](https://github.com/coin-or/python-mip/files/7304813/problem.py.zip)

Running the file gives me the output:
```bash
❯ python problem.py
STATUS: OptimizationStatus.OPTIMAL
Claimed minimum:   0.0407672349999999
----------MANUAL START RESULT----------
Actual minimum:   0.0
```

Within the file, the `test_graph` on line 82 can be replaced with another random graph, as long as the entries represent the minimum weighted path length between two vertices. I find the discrepancy between reported optimal and true optimal to still exist even when changing `test_graph`.

**Expected behavior**
I expect that when `m.optimize()` returns Optimal, the objective is actually minimized.

**Additional Info**
In the python file above, I test using a "trivial" problem that I know the answer must be zero. There are a couple other similar inputs for which I know the true minimum must be upper bounded by some value less than the optimization's output.

**Comment by tkralphs** [comment]
@tooflesswulf If you post an MPS file that replicates this in stand-alone Cbc to the Cbc project, then we can take a look.

**Comment by sebheger** [comment]
I have rerun the provided script with the latest master today. Looks fine

STATUS: OptimizationStatus.OPTIMAL
Claimed minimum:   0.0
----------MANUAL START RESULT----------
Actual minimum:   0.0

Could be declared as fixed with next release

**Comment by sebheger** [comment]
Fixed by https://github.com/coin-or/python-mip/milestone/2
