### ISSUE TITLE
reduced varable precision with m.write

### ISSUE THREAD

**Issue by mhechthz** [coin-or/python-mip#222]
I'm using small factors in my model. When I write a lp file using m.write('mylp.lp') only 5 digits are written. 

Since I'm working with chemical elements, small concentrations are usual. When I hand over the problem to CPLEX or another solver, I get different results due to precision loss.

I would expect that the precision can be defined arbritarily for m.write().

**Comment by tuliotoffolo** [comment]
We use the solver's ``write`` method, so this would have to change in CBC (and/or Gurobi).
