### ISSUE TITLE
CBC solver does not accept initial solution

### ISSUE THREAD

**Issue by FGlazov** [coin-or/python-mip#229]
**Describe the bug**
The CBC solver does not initialize from an initial feasible solution, if one is provided. It maybe has something to do with the variables added via add_var_tensors, I'm not sure.

There is a closed issue #44 which is of a similar nature.

**To Reproduce**
Running the following code

```python
from mip import Model, INTEGER, CONTINUOUS
from random import randint

m = Model("toy-model")

level1 = m.add_var_tensor(
    (8, 8),
    name='1',
    var_type=INTEGER,
    ub=10,
    lb=-10
)

level1_aux = m.add_var_tensor(
    (8, 8),
    name='1_aux',
    var_type=CONTINUOUS,
    ub=10,
    lb=-10,
    obj=1
)

level2 =  m.add_var_tensor(
    (4, 4),
    name='2',
    var_type=INTEGER,
    ub=10,
    lb=-10
)

level2_aux =  m.add_var_tensor(
    (4, 4),
    name='2_aux',
    var_type=CONTINUOUS,
    ub=10,
    lb=-10,
    obj=1
)

for base_var, aux_var in zip(level1.flatten(), level1_aux.flatten()):
    m += base_var <= aux_var
    m += -base_var <= aux_var
for base_var, aux_var in zip(level2.flatten(), level2_aux.flatten()):
    m += base_var <= aux_var
    m += -base_var <= aux_var

initial_solution = []
for x in range(0, 8):
    for y in range(0,8):
        value = randint(-10, 10)
        m += level1[x][y] + level2[x // 2][y // 2] == value
        initial_solution.append((level1[x][y], value))

m.start = initial_solution
m.optimize()
```

Results in the output

```
Cbc0045I Warning: MIPstart solution is not valid, column names do not match, ignoring it.
```

**Expected behavior**
The CBC solver should accept the initial solution and use it in order to improve performance.

**Desktop (please complete the following information):**
 - Operating System, version: Windows 10 with Linux subsystem (Ubuntu 20.04.1 LTS)
 - Python version: Python 3.8.10
 - Python-MIP version (we recommend you to test with the latest version):  1.13.0

**Additional context**

I noticed this behavior when I tried to dynamically create the levels described above (more than 2 levels) for a grid of values. The auxiliary variables are used for the sum of absolute values minimization trick: https://math.stackexchange.com/questions/623568/minimizing-the-sum-of-absolute-values-with-a-linear-solver/623569

**Comment by christian2022** [comment]
Just a wild guess: Have you tried changing your variable names to "regular" variable names, i.e. starting with a letter instead of a number?

**Comment by FGlazov** [comment]
I just tried it with 'first_level', 'first_aux', 'second_level', 'second_aux'. The bug still happens then.

**Comment by aphi** [comment]
I replicated this issue. It looks to come from the unset INTEGER variables stored in `level2`. (Your code only sets values for `level1`.) One workaround is just to add these two lines:

```python
for v in level2.flatten():
    initial_solution.append((v, 0.0))
```

Which then works for me, giving:
`Cbc0045I MIPStart provided solution with cost 324`

Ideally the MIPStart is meant to be a feasible solution specifying all integer values. Even though your code is compliant with the python-mip documentation which suggests 0 will be taken as a default for non-specified start values, it looks like this doesn't happen yet.

I'm keen to make some contributions to python-mip, so will have a look into why that is.

**Comment by sebheger** [comment]
Fixed by https://github.com/coin-or/python-mip/milestone/2
