### ISSUE TITLE
use other solvers to initialize mip.Model

### ISSUE THREAD

**Issue by brentian** [coin-or/python-mip#23]
mip.Model.__init__ provides a param `solver` to initialize the model instance, but it has not been used yet.  The attribute self.solver is created by `solver_name`, i.e., Gurobi or CBC.

Can we switch to something like `self.solver = solver` to make user specified solver possible? I actually want to try another interior-point solver and already implemented the Solver class.

**Comment by h-g-s** [comment]
The solver property of the Model object needs to informed in the __init__ constructor method since most methods of the Model class (e.g. to build the problem) translate the calls to solver specific methods. 

If you implemented a new Solver class implementing the required methods to call your specific solver then it should be very easy to incorporate this new solver in Python-MIP by adding a new if in the __init__ method of the model. I can provide some help if you run into some difficulties.

**Comment by sk-surya** [comment]
How to use CBC as the solver, but Gurobi as the LP solver inside CBC?

**Comment by h-g-s** [comment]
No.   Currently CBC supports CPLEX as an alternative LP solver, but it 
has to be compiled with that option.
​=============================================================
Haroldo Gambini Santos
Computing Department
Universidade Federal de Ouro Preto - UFOP
KU Leuven - CODeS
email: haroldo [at ] ufop.edu.br
       Haroldo.GambiniSantos@cs.kuleuven.br
home/research page: www.decom.ufop.br/haroldo 
<http://www.decom.ufop.br/haroldo/>


It has long been an axiom of mine that the little things are infinitely
the most important.

Em sex, 24 de abr de 2020 às 14:56, sk-surya 
<notifications@github.com> escreveu:

**Comment by sk-surya** [comment]
CPLEX is fine too. Could you tell me how to get compiled CBC with CPLEX? I'm on Windows 64 bit.

**Comment by h-g-s** [comment]
Hi,

I think that here:
<https://projects.coin-or.org/Osi>
There is some information on how to include CPLEX as one of the 
OsiAvailable solvers.


​=============================================================
Haroldo Gambini Santos
Computing Department
Universidade Federal de Ouro Preto - UFOP
KU Leuven - CODeS
email: haroldo [at ] ufop.edu.br
       Haroldo.GambiniSantos@cs.kuleuven.br
home/research page: www.decom.ufop.br/haroldo 
<http://www.decom.ufop.br/haroldo/>


It has long been an axiom of mine that the little things are infinitely
the most important.

Em sex, 24 de abr de 2020 às 20:23, sk-surya 
<notifications@github.com> escreveu:
