### ISSUE TITLE
Model.copy() fails with Cbc (invalid row index?)

### ISSUE THREAD

**Issue by rschwarz** [coin-or/python-mip#238]
**Describe the bug**
After building a model with CBC as solver, we call `model.copy()` which aborts Python.

**To Reproduce**
Code snippet:
```python
import mip

model = mip.Model(solver_name=mip.CBC)
x = model.add_var("x")
y = model.add_var("y")
z = model.add_var("z")

model.add_constr(x + y <= 4)     # 0
model.add_constr(x - y <= 1)     # 1
model.add_constr(y - x <= 1)     # 2
model.add_constr(y - x <= 1)     # 3, duplicate of 2
model.add_constr(z >= z)         # 4, trivial ==> removed by presolve?
model.add_constr(z == 2*x + 3*y) # 5

model.objective = mip.maximize(z)

status = model.optimize()
print(f"{status}, x={x.x}, y={y.x}, z={z.x}")
print()

model2 = model.copy()
status = model2.optimize()
print(f"{status}, x={x.x}, y={y.x}, z={z.x}")
```
Observed output:
```
$ python run.py
Welcome to the CBC MILP Solver 
Version: devel 
Build Date: Nov 15 2020 

Starting solution of the Linear programming problem using Dual Simplex

Coin0506I Presolve 3 (-2) rows, 2 (-1) columns and 6 (-5) elements
Clp0000I Optimal - objective value 10.5
Coin0511I After Postsolve, objective 10.5, infeasibilities - dual 0 (0), primal 0 (0)
Clp0032I Optimal objective 10.5 - 2 iterations time 0.002, Presolve 0.00
OptimizationStatus.OPTIMAL, x=1.5, y=2.5, z=10.5

Invalid row index (5), valid range is [0,5). At /home/travis/build/coin-or/Cbc/src/Cbc_C_Interface.cpp:2389
[1]    20185 abort      python run.py
```

**Expected behavior**
The model can be copied and both versions find the same solution.

**Desktop (please complete the following information):**
 - Operating System, version: Debian (stable, "Bullseye") Linux (5.10.0-10-amd64)
 - Python version: Python 3.9.2
 - Python-MIP version :  1.13.0 (via pip)

**Additional context**
A smaller version (with constraint `z >= z` removed) does work as expected. So my guess is that some constraints are removed to the solver in presolving. Interestingly, duplicate constraints are not detected/removed in the same way.

It might also be that the constraint (being "empty") is not added to Cbc in the first place, but then the reference to it in `Model.constrs` should also be removed?

Note that with model, not only `model.copy()` fails, but also, eg `model.constrs[5].name` or other queries about this last constraint which seems to be "out of bounds".

**Comment by sebheger** [comment]
@rschwarz Your problem has the same root cause as #213. Your "trivial" constraint is not "pushed" to the cbc on C-code side, but still kept in python's storage. I have already propsed PR #237 to fix this.

**Comment by rschwarz** [comment]
Yes, that makes sense. So, this issue may be closed as a duplicate.
