### ISSUE TITLE
Switch to CBC from Gurobi

### ISSUE THREAD

**Issue by bohonghellofresh** [coin-or/python-mip#240]
**Describe the bug**
Hi all, I tried to inspect the execution time of project with Gurobi and CBC, but on the Installation page of python mip and my practical experience, I found out if I installed the Gurobi, the mip will automatically choose Gurobi as solver, even I change the solver name to CBC: 

<img width="840" alt="Screenshot 2022-01-17 at 11 46 16" src="https://user-images.githubusercontent.com/93598066/149755903-5805b153-4e4a-4331-9131-2278ed36a68d.png">

Eventually I need to uninstall Gurobi to use CBC.

**Expected behavior**
switching the solver with changing the name of "solver_name"

**Desktop (please complete the following information):**

Operating System, version: macOS 11.5.2
Python version: 3.9.0
Python-MIP version (we recommend you to test with the latest version): 1.13.0

**Comment by tuliotoffolo** [comment]
Hello @bohonghellofresh,
I wasn't able to reproduce the bug. Would you mind including your code?

**Comment by tuliotoffolo** [comment]
Hi @bohonghellofresh,
Well, I've tried but could not reproduce the error here.

**Comment by bohonghellofresh** [comment]
@tuliotoffolo Thank you for trying to help!
I think it's my mistake that I forget to put solver_name attribute in the Model()
it's fixed after doing so.
Thanks again!
