### ISSUE TITLE
constr_by_name does not work

### ISSUE THREAD

**Issue by quangvu0702** [coin-or/python-mip#25]
I have tried the example but I cannot get the contrain by name. This is my code
![image](https://user-images.githubusercontent.com/3850242/69116556-5e93d780-0abf-11ea-8863-0206d5dcd67d.png)

**Comment by pmla** [comment]
I am having the same problem, with version 1.5.3.
My guess is that the `self._model` parameter has been omitted?

**Comment by h-g-s** [comment]
able to reproduce here,  fixing for next release

**Comment by h-g-s** [comment]
I think it is fixed in 1.6  ( we also included tests for this now ), could you please check ?

**Comment by quangvu0702** [comment]
It works now. Thank you very much.
