### ISSUE TITLE
Python-MIP interrupts output before time limit

### ISSUE THREAD

**Issue by Krasscheck** [coin-or/python-mip#287]
I created a MIP model with GAMS and with Python-MIP. Gams finds the optimal solution.

Python-Mip start computing, but interrupts the output before the given time limit. 

Operation System Windows 11 i9 processor: 

I startet with:  py sclsp.py > sclsp.out

The same model runs perfectly with other data (smaller problem size)

The attached file contains the complete python-mip model
[sclsp.py.txt](https://github.com/coin-or/python-mip/files/9053052/sclsp.py.txt)
[sclsp.out.txt](https://github.com/coin-or/python-mip/files/9053055/sclsp.out.txt)

**Comment by sebheger** [comment]
@Krasscheck Which python version and mip version are you using?

**Comment by Krasscheck** [comment]
This issue (from mip version 1.12) has disappeared in mip version 1.14.
