### ISSUE TITLE
Failed building wheel for cffi

### ISSUE THREAD

**Issue by emilyziech** [coin-or/python-mip#326]
**Describe the bug**
While attempting to install mip using pip on Windows, pip failed to build wheel for cffi, then also python setup.py bdist_wheel did not run successfully.

**To Reproduce**
pip install mip

**Expected behavior**
mip should be installed with no errors

**Desktop (please complete the following information):**
 - Operating System, version: Windows 11
 - Python version: Python 3.11
 - Python-MIP version (we recommend you to test with the latest version):  Latest

**Additional context**
Full output:
[MIP_install_output.txt](https://github.com/coin-or/python-mip/files/10326850/MIP_install_output.txt)

**Comment by jurasofish** [comment]
This is an issue with installing cffi.
Seems there are no prebuilt wheels for python 3.11 for the version of cffi that python mip requires and your computer doesn't have the required software to build it.
common issue, quickest and easiest solution for you would likely be to use python 3.10 instead.

**Comment by sebheger** [comment]
@emilyziech Python 3.11. is not supported by python-mip yet. As @jurasofish already stated above, you need to "downgrade" to python 3.10.

It is surprising to me, that pip lets you start to install python-mip under python 3.11. I will need to take a look at the pyproject.toml file trying to forbid this.

**Comment by sebheger** [comment]
Yep, we have no upper bound 
```requires-python = ">=3.7" ```

**Comment by sebheger** [comment]
@emilyziech I have released version an updated version 1.15 which includes support for python 3.11. Would you be so kind to confirm that you can now install it successfully?

**Comment by sebheger** [comment]
@emilyziech I will close this issue, as i would consider this to be solved with release 1.15.0
