### ISSUE TITLE
Incorrect file extension when call write() with CBC solver

### ISSUE THREAD

**Issue by alexander-popkov** [coin-or/python-mip#348]
**Describe the bug**
When I call method `model.write('model.mps')`, I get a file model.mps.mps.gz instead of model.mps.

**To Reproduce**
The bug happens when I run such script:
```
m = mip.Model(solver_name=mip.CBC)
m.read('model.lp')
m.write('model.mps')
```
It arises only for CBC solver

**Expected behavior**
I expect to get a model in the format `.mps`

**Desktop (please complete the following information):**
 - Operating System, version: Windows 10, MacOS 13
 - Python version: 3.9
 - Python-MIP version (we recommend you to test with the latest version):  1.15.0

**Comment by sebheger** [comment]
Thanks for reporting @alexander-popkov

I will close this issue as it is duplicate to #164
