### ISSUE TITLE
help support mac arm

### ISSUE THREAD

**Issue by suzhenyu22** [coin-or/python-mip#365]
I compile cbc of mac arm, and fork new branch, and test.

the attch file on here.
[cbc-c-darwin-arm64.zip](https://github.com/coin-or/python-mip/files/13958051/cbc-c-darwin-arm64.zip)

we should change cbc.py on line 98:
```
from platform import machine as platform_machine

elif platform.lower().startswith("darwin") or platform.lower().startswith("macos"):
    if platform_machine().lower().startswith("arm64"):
        libfile = os.path.join(pathlib, "cbc-c-darwin-arm64.dylib")
    else:
        libfile = os.path.join(pathlib, "cbc-c-darwin-x86-64.dylib")

```

**Comment by tuliotoffolo** [comment]
Thanks, your contribution highly appreciated!
I actually got myself a Mac M1 these days, and will work to update Python-MIP to the latest CBC version. I'll update the code following your suggestions.

**Comment by tuliotoffolo** [comment]
FYI: I also compiled the binary and included the script I used to produce the binary it in the repo. I've mentioned you in the code change to detect if the ARM64 binary should be used.
