### ISSUE TITLE
Feature Request: max_seconds_no_change

### ISSUE THREAD

**Issue by rodo-hf** [coin-or/python-mip#40]
Is it possible to have an additional stop-condition that stops if for x seconds the solution didn't improve? It would be also good to pass in the same time a minimum and a maximum seconds.

**Comment by h-g-s** [comment]
Hi,
I think that this would be a good addition. I would also include max_nodes_without_improving_sol
Just to confirm if my view of this feature is the same as yours, while NO FEASIBLE solution is found the solver would not exit, only after finding a feasible solution and spending some processing without improving it, is it ?

**Comment by rodo-hf** [comment]
Hi,
yes we understand in the same way. The second_count should start with the first feasible solution. 

Make sure, that it is not conflicting with max_mip_gap and max_seconds. The condition which is first true, triggers the exit.

**Comment by rodo-hf** [comment]
Hi Haraldo,

when do you expect to implement that feature?

Thanks in advance.

**Comment by h-g-s** [comment]
Hi @rodo-hf ,  this feature is implemented in 1.10,  we now provide

max_seconds_same_incumbent max_nodes_same_incumbent , could you check ?
