### ISSUE TITLE
Can variable index on tuple set ?

### ISSUE THREAD

**Issue by qtbhappy** [coin-or/python-mip#46]
Hi. I wonder if we can define variable indexing on tuple set? Like the following:
 tuple set Arc = {<1,1>,<1,2>, <1,3>, <2,3>};

float+ var x[a in Arc]; //variable on tuple set Arc

**Comment by h-g-s** [comment]
this would be:
from mip import *

m = Model()
Arcs = [(1, 1), (1, 2), (1, 3)]

# create vars
x = {a: m.add_var() for a in Arcs}

# constraint to select one arc
m += xsum(x[a] for a in Arcs) == 1
