### ISSUE TITLE
any plan to support cplex?

### ISSUE THREAD

**Issue by qtbhappy** [coin-or/python-mip#49]
Sir, do you have any plan to support cplex solver?

**Comment by tuliotoffolo** [comment]
Yes! We plan to add support to cplex and scip solvers.
Em 2 de jan de 2020 23:38 -0300, qtbhappy <notifications@github.com> escreveu:

**Comment by qtbhappy** [comment]
Do you have a time frame to support cplex?

**Comment by tuliotoffolo** [comment]
We definitely plan to support Cplex! However, there is no time frame yet.
Em 28 de jan de 2020 23:11 -0300, qtbhappy <notifications@github.com>, escreveu:

**Comment by quantcn** [comment]
After one year, do you have a time frame to support cplex now?
