### ISSUE TITLE
Use logging module instead of print

### ISSUE THREAD

**Issue by adrian-antonczyk** [coin-or/python-mip#50]
Currently there are various random print function calls. For example: https://github.com/coin-or/python-mip/blob/a836a7198dc0e4b08e15d92f11f26039f2ebff96/mip/model.py#L1277 
It would be great if it could be migrated to some logging module (i.e. https://docs.python.org/3/library/logging.html) so that package output could be managed/configured/suppressed easily.

**Comment by h-g-s** [comment]
Hi @adrian-antonczyk ,  thanks for the suggestion.
In the current approach each MIP model has the property    verbose     that can be used to suppress messages related to the solution of a MIP model.  The specific message you mentioned is a module level message that right now cannot be suppressed. I'm not familiar with the Python logging options, I'll check it.
One thing related to messages that is on my TODO list (but would involve a lot of work to work well) is the production of unified messages independently of the solver used (CBC or GUROBI). RIght now each solver prints its own messages (which are different) .  Ideally I would like to disable solver specific messages and provide an unified output (using callbacks) to display the progress.

**Comment by uurriola** [comment]
I updated the code by @amarvin in #86 
@h-g-s use of logging allows to define custom formatting and level. Basic example to show/hide the current printed messages would start with:
* To show all messages
```
import logging
logging.basicConfig(level='INFO')

import mip

my_model = mip.Model()
...
```
* To hide info, we can just set level to "ERROR"/"CRITICAL":
```
import logging
logging.basicConfig(level='ERROR')

import mip

my_model = mip.Model()
...
```

I think it is the best solution to use the logging module for easier integration in calling apps. 

As mentioned in the pull request, there are still some prints I am not able to remove (from CBC itself I guess, but I can't find them in the code).
