### ISSUE TITLE
CBC not found

### ISSUE THREAD

**Issue by sclereid** [coin-or/python-mip#60]
I just managed to install `mip` for plain python 3.8.1 on windows (via `pip install mip`). Trying a simple test yields the following error:

```python
C:\Users\user>python
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from mip import *
Using Python-MIP package version 1.7.2
>>> m = Model()
cbc not found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mip\model.py", line 119, in __init__
    from mip.cbc import SolverCbc
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mip\cbc.py", line 455, in <module>
    Osi_getNumCols = cbclib.Osi_getNumCols
NameError: name 'cbclib' is not defined
```

I assumed that CBC is included with `mip`, as stated in
> The default installation includes pre-compiled libraries of the MIP Solver CBC for Windows, Linux and MacOS. If you have the commercial solver Gurobi installed in your computer, Python-MIP will automatically use it as long as it finds the Gurobi dynamic loadable library. Gurobi is free for academic use and has an outstanding performance for solving MIPs. Instructions to make it accessible on different operating systems are included bellow.

I have no idea why this happens, and got no hint to solve this problem. What's wrong?

**Comment by h-g-s** [comment]
Try python 64 bits,  we dropped support for 32 bits.

Em qui, 20 de fev de 2020 23:03, sclereid <notifications@github.com>
escreveu:

**Comment by sclereid** [comment]
> Try python 64 bits, we dropped support for 32 bits. Em qui, 20 de fev de 2020 23:03, sclereid <notifications@github.com> escreveu:
> […](#)

Thanks, I reinstalled python and it works now.
