### ISSUE TITLE
Slow extraction of variable values

### ISSUE THREAD

**Issue by mjdv** [coin-or/python-mip#61]
Generally when I optimize a model, I need to afterwards extract the values of the variables. This can take quite long: often much longer than the actual optimization.

Yesterday I solved a version of the assignment problem with python-mip. The model has about 500,000 variables, all binary, and about 100,000 constraints. Optimizing the model takes 3 seconds. Obtaining the values of all binary variables, using the same method (`var.x` for each variable `var`) as in the examples in the documentation, takes nearly 4 minutes.

This is consistent with other python-mip programs I have written, and a small variety of systems on which I have run them. (If the details matter I can provide them.)

Is there perhaps a faster way to extract the values of the variables than reading `var.x` for each variable separately?

**Comment by tuliotoffolo** [comment]
Thank you for your comment, Mees.
Just to be sure: you are using CBC, right?

Good news is that we will be able to improve this very soon (by directly accessing results from CBC and removing some checks). It should be faster in the next version.

Additionally, we plan to include ways of getting the entire solution at once. We might use numpy for that; we've been discussing this...
Please check the next version!
Em 21 de fev de 2020 11:37 -0300, Mees de Vries <notifications@github.com>, escreveu:

**Comment by h-g-s** [comment]
Also, are you using the standard Python (CPython)  or  Pypy ?

**Comment by mjdv** [comment]
Hi @tuliotoffolo, yes, I am using CBC. In fact, a friend using the Gurobi back-end let me know that extracting the variables (for the same program) is nearly instantaneous. In that case I look forward to the new version. :-)

Hi @h-g-s, I have tried both, and the difference is pretty much negligible.

**Comment by h-g-s** [comment]
Hi @mjdv ,   Python-MIP 1.8 is out. It should be ~30 times faster to query the solution values for variables.  Could you test ??? I'll close the issue, please re-open it if the problem persists. Cheers
