### ISSUE TITLE
The constructor freezes

### ISSUE THREAD

**Issue by FlorianDietz** [coin-or/python-mip#68]
I have a situation where my program freezes when I call `mip.Model(sense=mip.MAXIMIZE)`

The program just freezes and becomes unresponsive. I receive no error message.

This happens after I have already run a number of models beforehand. The error is reproducible for me: It always freezes at exactly the same point, after having done dozens of other optimizations without issue. I can not give you a code example, because it's proprietary code. I also don't know how to reproduce it on a toy example. I have no idea why this one method call suddenly makes everything freeze. Especially because this happens in the constructor, so it can't have anything to do with the constraints or optimization function.

Also, using importlib.reload(mip) does not help.

**Comment by h-g-s** [comment]
Hi @FlorianDietz .  It is very hard to debug without a code example. Perhaps you could run step-by-step the constructor in the call where it freezes (assuming the you know at which iteration it happens).

**Comment by h-g-s** [comment]
running it step-by-step would perhaps indicate at which line it freezes...

**Comment by sebheger** [comment]
@FlorianDietz Do you still observe the problem with the latest mip version?

**Comment by rschwarz** [comment]
Could this be a license issue, ie the failure to get a new Gurobi environment, with the previously used ones not yet released?

**Comment by FlorianDietz** [comment]
I no longer work there and do not remember what this bug was about.
