### ISSUE TITLE
cbc not loading win10 and pypy

### ISSUE THREAD

**Issue by fabioO11** [coin-or/python-mip#72]
Hi guys,

I get this error 
"
Osi_getNumCols = cbclib.Osi_getNumCols
NameError: name 'cbclib' is not defined
"
if I try to solve any problem using PyPy3.6 v7.3.0.
Python-MIP version is 1.7.2 and win10
Is this because of x86/x64 ?
If it's the case, can you suggest me an older version working with pypy?
Thanks!

Fabio

**Comment by h-g-s** [comment]
Hi, is you Pypy 64 bits ? Right now we only support 64 bits installations.

**Comment by fabioO11** [comment]
Hi Haroldo,
AFAIK there is no full 64 bits win version of pypy.
That's the reason why I was asking for an older version working with pypy 32 bits.
In my opinion it would be a loss not to be able to use the package with pypy on win machines.

Fabio

**Comment by liam-veitch** [comment]
@fabioO11 have you tried using python-mip/Pypy under Windows Subsystem for Linux?

**Comment by fabioO11** [comment]
> @fabioO11 have you tried using python-mip/Pypy under Windows Subsystem for Linux?

No, I haven't tried it, but in my opinion it's a pity not to be able to use the package with pypy on a "standard" win machine (as it is for linux). Btw I really appreciate the mip package as I find it really handy.

**Comment by tkralphs** [comment]
WSL is available on a "standard" Win machine and there's hardly any difference between running the WSL Python versus native Windows. If you install a nice terminal program, like [Fluent](https://github.com/felixse/FluentTerminal), that can start WSL, Powershell, and Windows command shells in different tabs or use Visual Studio Code to run your Python scripts, you would hardly even know you are using WSL. Wit that said, there are 32-bit binaries that I guess would work [here](https://bintray.com/coin-or/download/Cbc/master). They are built with MinGW compilers, but I think @h-g-s said that the 64-bit MinGW DLLs do work.
