### ISSUE TITLE
[QUESTION] Switch-off print

### ISSUE THREAD

**Issue by rodo-hf** [coin-or/python-mip#77]
Hi, is it possible to switch off the print of the solver?

**Comment by h-g-s** [comment]
model.verbose = 0

Em dom, 29 de mar de 2020 18:03, rodo-hf <notifications@github.com>
escreveu:

**Comment by rodo-hf** [comment]
It is still showing:

> Starting solution of the Linear programming relaxation problem using Primal Simplex

Also possible to disable showing that?

**Comment by h-g-s** [comment]
Should be fixed in 1.8.2.  I'll close, please report if it still happening.
