### ISSUE TITLE
max_seconds doesn't stop 

### ISSUE THREAD

**Issue by borgr** [coin-or/python-mip#78]
I run an active learning core-set solution based on mip. (See original code in gurobi [here](https://github.com/dsgissin/DiscriminativeActiveLearning/blob/master/query_methods.py))

For some reason the code doesn't stop for very long times, even though it has a max_seconds parameter set (I tested on windows but also on linux)

`    def mip_model(self, representation, labeled_idx, budget, delta, outlier_count, greedy_indices=None):

        model = mip.Model("Core Set Selection")
        # set up the variables:
        points = {}
        outliers = {}
        feasible_start = []
        for i in range(representation.shape[0]):
            if i in labeled_idx:
                points[i] = model.add_var(ub=1.0, lb=1.0, var_type=BINARY, name="points_{}".format(i))
            else:
                points[i] = model.add_var(var_type=BINARY, name="points_{}".format(i))
        for i in range(representation.shape[0]):
            name = "outliers_{}".format(i)
            outliers[i] = model.add_var(var_type=BINARY, name=name)
            # outliers[i].start = 0
            feasible_start.append((outliers[i], 0.0))

        # initialize the solution to be the greedy solution:
        if greedy_indices is not None:
            for i in greedy_indices:
                # points[i].start = 1.0 # gurobi
                feasible_start.append((points[i], 1))
            model.start = feasible_start
        # set the outlier budget:
        model.add_constr(xsum(outliers[i] for i in outliers) <= outlier_count, "budget")

        # build the graph and set the constraints:
        model.add_constr(xsum(points[i] for i in range(representation.shape[0])) == budget, "budget")
        neighbors = {}
        graph = {}
        print("Updating Neighborhoods In MIP Model...")
        for i in range(0, representation.shape[0], 1000):
            print("At Point " + str(i))

            if i + 1000 > representation.shape[0]:
                distances = self.get_distance_matrix(representation[i:], representation)
                amount = representation.shape[0] - i
            else:
                distances = self.get_distance_matrix(representation[i:i + 1000], representation)
                amount = 1000

            distances = np.reshape(distances, (amount, -1))
            for j in range(i, i + amount):
                graph[j] = [(idx, distances[j - i, idx]) for idx in
                            np.reshape(np.where(distances[j - i, :] <= delta), (-1))]
                neighbors[j] = [points[idx] for idx in np.reshape(np.where(distances[j - i, :] <= delta), (-1))]
                neighbors[j].append(outliers[j])
                model.add_constr(xsum(neighbors[j]) >= 1, "coverage+outliers")

        model.__data = points, outliers
        model.emphasis = 1
        model.threads = -1
        # model.max_seconds = self.max_seconds
        model.optimize(max_seconds=self.max_seconds, max_nodes=self.max_nodes) # <<<<<<<< this may be short but can also be very long

        return model, graph`

**Comment by h-g-s** [comment]
Hi,  which are the last messages printed by CBC when   model.verbose = 1 ?
